### ISSUE TITLE
RAM and CPU value occasionally show full float values

### ISSUE THREAD

**Issue by travis-fm** [LucasTonetto/vscode_performance_metrics#1]
Hey there, first off thanks for the extension! I've been using it for Docker development to monitor resource usage during builds and it's perfect to watch RAM and CPU usage without having to have additional windows open.

Most of the time the decimals are properly rounded, but occasionally the RAM and CPU values will display the full float values, versus being limited to two decimals, like below:
![image](https://github.com/user-attachments/assets/0a549b19-7e74-4ccd-810d-d7ccbd8b443b)

Floating point arithmetic isn't exact, and even though you're fixing the two starting variables, the end subtraction result can still show wonky values like above unless you explicitly round the final value.

I haven't worked with JS in a long time, but I'm pretty sure you just need to add two additional toFixed() calls for `usage_ram_gb` and `cpu_usage` to make sure the final values are properly rounded. You could maybe remove the two previous calls as well to get a more accurate result (probably a trivial difference.)

Something like:
```javascript
while(1) {
	const free_ram = os.freemem();
	const total_ram = os.totalmem();
        
        // Remove toFixed()
	const free_ram_gb = (free_ram/(1024*1024*1024));
        // Remove toFixed()
	const total_ram_gb = (total_ram/(1024*1024*1024));

        // Fix final RAM usage to 2 decimals
	const usage_ram_gb = (parseFloat(total_ram_gb) - parseFloat(free_ram_gb)).toFixed(2);
        // Fix final CPU usage to 2 decimals
	const cpu_usage = await cpuUsage().toFixed(2);
        // Create "display" variable for total_ram_gb and fix that to 2 decimals
        const usage_ram_gb_display = total_ram_gb.toFixed(2);

	statusBarItem.text = `RAM: ${usage_ram_gb}/${total_ram_gb_display} GB`;
	statusBarItem.text += `\tCPU: ${cpu_usage}%`;
	await new Promise(r => setTimeout(r, 1000));
}
```

EDIT: Just realized you're displaying `total_ram_gb` at the end as well. I'd add another variable that's fixed and use that for the display instead of the calculation variable. Changed my example above.

**Comment by LucasTonetto** [comment]
Hello, @GibsonSoft , how are you?

First of all, thank you very much for your feedback. I’m glad the extension has been useful for you. I apologize for the delay in fixing the issue; I’ve been busy over the past few weeks.

I have released version 1.0.2 of the extension, where I have fixed the rounding error. It is now available in the marketplace. Thank you very much :)

If you encounter any issues, please let me know.

![image](https://github.com/user-attachments/assets/11e35bdd-55a9-4a99-b3ae-fe712b1550ae)
